config/routes.rb
OnlineTicketApp::Application.routes.draw do
  

  resources :ticket_orders

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  root :to => 'dashboard#index'
  resources :users
  resources :sessions
  resources :tickets
  resources :ticket_orders do
    member do
      get 'check_out'
    end
  end
  namespace :admin do
    resources :tickets
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :code, :departure, :destination, :ticket_type, :ticket_class, :user_id, :is_ordered
  has_one :ticket_order
  validates :code,  :presence => true , :uniqueness => true
  validates :departure,  :presence => true
  validates :destination,  :presence => true
  validates :ticket_type,  :presence => true
  validates :ticket_class,  :presence => true
  validate :check_departure

  def check_departure
    errors.add(:departure, "error : Please complete your departure date and time") if departure.nil?
  end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::ApplicationController
  before_filter :find_ticket,  :only => [:edit, :update, :destroy, :show]
  before_filter :require_admin_login
  def index
    @tickets = Ticket.all
  end

  def show;
  end

  def new
    @ticket = Ticket.new
  end

  def edit;
  end

  def create
    @ticket = Ticket.new(params[:ticket].merge(:is_ordered => false))
    if @ticket.save
      redirect_to admin_tickets_path, :notice => 'Ticket was successfully created.'
    else
      render :action => "new", :notice => 'Ticket was failed created.'
    end
  end

  def update
    if @ticket.update_attributes(params[:ticket])
      redirect_to admin_tickets_path, :notice => 'Ticket was successfully updated.'
    else
      render :action =>"edit", :notice => 'Ticket was failed updated.'
    end
    
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_path, :notice =>"Ticket was successfully deleted"
  end

  private
  def find_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_ticket,  :only => [:show]
 
  def index
    @tickets = Ticket.where("is_ordered = false")
  end

  def show;  end

  private
  def find_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/_form.html.erb
<div class="form_ticket">
  <%= form_for(@ticket , :url => admin_tickets_path) do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
          <% @ticket.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <ul class="form">
      <li>
        <%= f.label :code %>:
      </li>
      <li>
        <%= f.text_field :code %>
      </li>
      <li>
        <%= f.label :destination %>:
      </li>
      <li>
        <%= f.text_field :destination %>
      </li>
      <li>
        <%= f.label :ticket_type %>:
      </li>
      <li>
        <%= f.select :ticket_type , options_for_select(["Luar Negeri", "Domestik"])%>
      </li>
      <li>
        <%= f.label :ticket_class %>:
      </li>
      <li>
        <%= f.select :ticket_class, options_for_select(["VVIP", "VIP", "Bisnis"])%>
      </li>
      <li>
        <%= f.label :departure_date%> :<br />
        <%= datetime_select("ticket", "departure", :prompt => true)%>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </li>
      <br />
      <div class="actions">
        <%= f.submit %>
      </div>
    </ul>
  <% end %>
</div>

app/views/admin/tickets/edit.html.erb
<h1>Editing ticket</h1>

<div class="form_ticket">
  <%= form_for(@ticket , :url => admin_ticket_path(@ticket), :method => :PUT) do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
          <% @ticket.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <ul class="form">
      <li>
        <%= f.label :code %>
        <%= f.text_field :code %>
      </li>
      <li>
        <%= f.label :destination %>
        <%= f.text_field :destination %>
      </li>
      <li>
        <%= f.label :ticket_type %>
        <%= f.select :ticket_type , options_for_select(["Luar Negeri", "Domestik"])%>
      </li>
      <li>
        <%= f.label :ticket_class %>
        <%= f.select :ticket_class, options_for_select(["VVIP", "VIP", "Bisnis"])%>
      </li>
      <li>
        <%= f.label :departure_date%> :<br />
        <%= datetime_select("ticket", "departure", :prompt => true)%>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </li>
      <div class="actions">
        <%= f.submit %>
      </div>
    </ul>
  <% end %>
</div>

<%= link_to 'Show', admin_ticket_path(@ticket) %> |
<%= link_to 'Back', admin_tickets_path %>

app/views/admin/tickets/index.html.erb
<h1>Listing tickets</h1>

<table border="1">
  <tr>
    <th>No</th>
    <th>Code</th>
    <th>Departure</th>
    <th>Destination</th>
    <th>Type</th>
    <th>Class</th>
    <th>Status</th>
    <th>Want to order ?</th>
    <th colspan="3">Action</th>
  </tr>

  <% @tickets.each_with_index do |ticket, i | %>
    <tr>
      <td><%= i + 1%></td>
      <td><%=ticket.code%></td>
      <td><%= ticket.departure.strftime("%d %B %y at %H:%M") unless ticket.departure.nil? %></td>
      <td><%=ticket.destination%></td>
      <td><%=ticket.ticket_type%></td>
      <td><%=ticket.ticket_class%></td>
      <td><%= ticket.is_ordered == true ? "Ordered": "Free"%></td>
      <% unless ticket.is_ordered %>
        <td> <%= link_to 'Order', new_ticket_order_path(:ticket_id => ticket.id)%> </td>
      <%else%>
        <td> Ordered  </td>
      <%end%>
      <%if current_user.email == "admin@admin.com"%>
        <td><%= link_to 'Show', admin_ticket_path(ticket) %></td>
        <td><%= link_to 'Edit', edit_admin_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', admin_ticket_path(ticket), :confirm => 'Are you sure?', :method=> :delete %></td>
      <%end%>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Ticket', new_admin_ticket_path if current_user.email == "admin@admin.com" %>

app/views/admin/tickets/new.html.erb
<h1 style="text-align: left">New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_tickets_path %>

app/views/admin/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li>Code : <%= @ticket.code %></li>
  <li>Departure Date : <%= @ticket.departure.strftime("%d %B %Y") %></li>
  <li>Departure Time : <%= @ticket.departure.strftime("%H : %M ") %></li>
  <li>Destination : <%= @ticket.destination %></li>
  <li>Type : <%= @ticket.ticket_type %></li>
  <li>Class : <%= @ticket.ticket_class %></li>
</ul>
<%= link_to 'Edit', edit_admin_ticket_path(@ticket) %> |
<%= link_to 'Back', admin_tickets_path %>