config/routes.rb
OnlineTicketApp::Application.routes.draw do
  

  resources :ticket_orders

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  root :to => 'dashboard#index'
  resources :users
  resources :sessions
  resources :tickets
  resources :ticket_orders do
    member do
      get 'check_out'
    end
  end
  namespace :admin do
    resources :tickets
  end

end

app/models/ticket_order.rb
class TicketOrder < ActiveRecord::Base
  attr_accessible :order_number, :order_date, :sit_number, :ticket_id, :user_id, :is_paid
  belongs_to :user
  belongs_to :ticket
  validates :sit_number , :presence => true,  :uniqueness => {:message => " has ordered"}
  validates :ticket_id  , :presence => true
  validates :order_number  , :presence => true,  :uniqueness => true
  
end

app/controllers/ticket_orders_controller.rb
class TicketOrdersController < ApplicationController
  before_filter :require_login
  before_filter :find_ticket_order, :only =>[:edit, :update, :destroy, :check_out]

  def index
    if current_user && !current_user.is_admin?
      @ticket_orders = TicketOrder.where("user_id = #{current_user.id}")
    elsif 
      @ticket_orders = TicketOrder.all
    end
  end

  def show
    @ticket_order = TicketOrder.find(params[:id])
  end

  def new
    tickets =  Ticket.where("is_ordered is false")
    @tickets = tickets.map{|x| [x.code,x.id]}  if tickets
    @ticket_order = TicketOrder.new
    if params[:ticket_id]
      @ticket_id = params[:ticket_id]
    end
  end

  def edit
    @tickets = Ticket.where("is_ordered is false").map{|x| [x.code,x.id]} << ["#{@ticket_order.ticket.code}","#{@ticket_order.ticket.id}"]
    @ticket_id = @ticket_order.ticket.id
    if @ticket_order.is_paid
      flash[:notice] = 'This Order has been paid.'
      redirect_to ticket_orders_path
    end
  end

  def create
    @ticket_order = TicketOrder.new(params[:ticket_order].merge(:order_date => Time.now, :is_paid => false))
    if @ticket_order.save
      Ticket.find(params[:ticket_order][:ticket_id]).update_attribute(:is_ordered, true)
      redirect_to ticket_orders_path, :notice=> 'Ticket order was successfully created.'
    else
      render :action =>"new"
    end
  end
  
  def update    
    if @ticket_order.update_attributes(params[:ticket_order])
      redirect_to ticket_orders_path, :notice=> 'Ticket order was successfully updated.'
    else
      render :action=> "edit"
    end
  end

  def destroy    
    @ticket_order.destroy
    redirect_to ticket_orders_path, :notice=> 'Ticket order was successfully deleted.'
  end

  def check_out   
    unless current_user.card_number.nil? or current_user.card_number == ""
      @ticket_order.update_attribute(:is_paid , true)
      flash[:notice] = 'Ticket order was successfully paid.'
    else
      flash[:notice] = 'Please complete your credit card number first.'
      redirect_to edit_user_path(current_user)
    end
  end

  private
  def find_ticket_order
    @ticket_order = TicketOrder.find(params[:id])
  end
end

app/helpers/ticket_orders_helper.rb
module TicketOrdersHelper
end

app/views/ticket_orders/_form.html.erb
<%= form_for(@ticket_order) do |f| %>
  <% if @ticket_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_order.errors.count, "error") %> prohibited this ticket_order from being saved:</h2>
      <ul>
        <% @ticket_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_ticket">
    <ul class="form">
      <li>
        <%= f.label :ticket%> :
        <%if params[:action] == 'edit'%>
          <%#raise @ticket_id.inspect%>
          <%= f.select :ticket_id, options_for_select(@tickets, :selected => @ticket_id )%>
        <%else%>
          <%= f.select :ticket_id, options_for_select(Ticket.where("is_ordered is false").map{|x| [x.code,x.id]}, :selected => @ticket_id)%>
        <%end%>
        
      </li>
      <li>
        <%= f.label :order_number%> :
        <%= f.text_field :order_number%>
      </li>
      <li>
        <%= f.label :order_date%> : <%= Time.now.strftime("%d %B %y")%>
      </li>
      <li>
        <%= f.label :sit_number%> :
        <%= f.text_field :sit_number%>
      </li>
      <div class="actions">
        <%= f.submit %>
      </div>
      <%= f.hidden_field "user_id", :value => current_user.id %>
    </ul>
  </div>
<br />
<% end %>

app/views/ticket_orders/check_out.html.erb
<h1>Your Order Info :</h1>
<ul>
  <h3>Your Info </h3>
  <li>Name : <%= current_user.name %></li>
  <li>Address : <%= current_user.address %></li>
  <li>Card Number : <%= current_user.card_number %></li>
  <li>Email : <%= current_user.email %></li>
  <li>Address : <%= current_user.address %></li>
  <h3>Order : </h3>
  <li>Order Number : <%= @ticket_order.order_number %></li>
  <li>Order Date : <%= @ticket_order.order_date %></li>
  <li>Sit Number : <%= @ticket_order.sit_number%></li>
  <h3>Your Check Out Number is : </h3>
  <%="#{@ticket_order.order_number}-#{@ticket_order.ticket.ticket_class}-#{@ticket_order.order_date.strftime('%d%m%y')}"%>
</ul>

<%=link_to "Back", ticket_orders_path %> | <%= link_to "Home", root_path %><br /><br />

app/views/ticket_orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

app/views/ticket_orders/index.html.erb
<h1>Listing of My ticket orders</h1>

<table border="1">
  <tr>
    <th>Order number</th>
    <th>Ticket number</th>
    <th>Order date</th>
    <th>Name</th>
    <th>Sit Number</th>
    <th>Status</th>
    <th>Payment</th>
    <th colspan="3">Action</th>
  </tr>

  <%if @ticket_orders%>
    <% @ticket_orders.each do |to| %>
      <tr>
        <td><%= to.order_number %></td>
        <td><%= to.ticket.code %></td>
        <td><%= to.order_date.strftime("%d %B %y") if to.order_date.present?%></td>
        <td><%= to.user.name %></td>
        <td><%= to.sit_number %></td>
        <td><%= to.is_paid == false ? "Unpaid" : "Paid"%></td>
        <td>
          <%if to.is_paid == false%>
            <%= link_to "Check Out", check_out_ticket_order_path(to)%>
          <%else%>
            Close
          <%end%>
        </td>
        <%if current_user.is_admin?%>
        <%unless to.is_paid%>
          <td><%= link_to 'Edit', edit_ticket_order_path(to) %></td>
        <%else%>
          <td>cannot edited</td>
        <%end%>
        <td><%= link_to 'Destroy', to, confirm: 'Are you sure?', :method=>:delete %></td>
        <%end%>
        <td><%= link_to 'Show', to %></td>

      </tr>
    <% end %>
  <%end%>
</table>

<br />

<%= link_to 'New Ticket order', new_ticket_order_path %> |
<%= link_to 'Home', root_path %>

app/views/ticket_orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>
<%if params[:ticket_id]%>
  <%if current_user.is_admin?%>
    <%= link_to 'Back', admin_tickets_path %>
  <%else%>
    <%= link_to 'Back', tickets_path %>
  <%end%>
<%else%>
  <%= link_to 'Back', ticket_orders_path %>
<%end%>

app/views/ticket_orders/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <ul>
    <li>Ticket Code : <%= @ticket_order.ticket.code %></li>
    <li>Order Number : <%= @ticket_order.order_number %></li>
    <li>Order Date : <%= @ticket_order.order_date.strftime("%d %B %y")%></li>
    <li>Sit Number : <%= @ticket_order.sit_number %></li>
    <li>Status : <%= @ticket_order.is_paid == false ? "Unpaid" : "Paid"%></li>
  </ul>
</div>

<%= link_to 'Edit', edit_ticket_order_path(@ticket_order) if current_user.is_admin? %> <br />
<%= link_to 'Back', ticket_orders_path %>