config/routes.rb
OnlineTicketApp::Application.routes.draw do
  

  resources :ticket_orders

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  root :to => 'dashboard#index'
  resources :users
  resources :sessions
  resources :tickets
  resources :ticket_orders do
    member do
      get 'check_out'
    end
  end
  namespace :admin do
    resources :tickets
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineTicketApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div style="width: 900px;border: 1px solid grey; margin-left: 180px; margin-right:100px; padding-left: 50px;padding-right: 50px; position: fixed">
      <h1 style="text-align: center">ONLINE TICKET</h1>
      <%= raw(welcome_text) %>
      <br />
      <hr />
      <%=flash[:notice]%>
      <%=flash[:error]%>
      <%if current_user  %>
        <div style="border: 1px solid red; height: 50px;">
          <ul style="float: left; width: 100%">
            <%if current_user.is_admin?%>
              <li class="menu"><%= link_to 'List Ticket', admin_tickets_path %></li>
            <%else%>
              <li class="menu"><%= link_to 'List Ticket', tickets_path %></li>
            <%end%>
            <li class="menu"><%= link_to 'Order Ticket', ticket_orders_path %></li>
            <li class="menu"><%= link_to 'Edit My Info', edit_user_path(current_user) %></li>
            <li class="menu"><%= link_to 'Homepage', root_path%></li>
          </ul>
        </div>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>